minimumReleaseAge: 0
minimumReleaseAgeExclude:
  - '@schema-platform/platform-shared@1.0.0'
  - '@schema-platform/platform-shared@1.0.1'
  - '@schema-platform/platform-shared@1.0.2'
onlyBuiltDependencies:
  - esbuild
  - vue-demi
  - '@parcel/watcher'
